---
- name: 'cleanup | Ensure locally stored files are removed'
  ansible.builtin.file:
    state: 'absent'
    path: '{{ _crt_local_dest_path }}/{{ inventory_hostname }}'
  delegate_to: 'localhost'
  become: true

- name: 'cleanup | Ensure parent directory of fetched certificates is removed: {{ _crt_local_dest_path }}'
  ansible.builtin.file:
    state: 'absent'
    path: '{{ _crt_local_dest_path }}'
  delegate_to: 'localhost'
  become: true
  when:
    - '_crt_remove_local_dest_path is defined'
    - '_crt_remove_local_dest_path'
...
